Vagrant.configure(2) do |config|
  config.vm.define 'ceph-devel'
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder "shared/", "/srv/shared"
  config.vm.hostname = 'ceph-devel'

  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id,
                  '--memory', 2048]
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'provisioning/ceph.yml'
    ansible.groups = {
      'ceph' => ['ceph-devel']
    }
  end
end

