Vagrant.configure(2) do |config|
  config.vm.define 'ceph1'
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 'ceph1'
  config.vm.synced_folder "shared/", "/srv/shared"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id,
                  '--memory', 2048]
  end
end

